apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-proxy
    role: proxy
  name: redis-proxy
spec:
  containers:
  - name: proxy
    image: aledbf/redis-alpine:v0.1
    ports:
    - containerPort: 6379
      name: api
